apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: replicator-deployment
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: replicator
    spec:
      serviceAccountName: replicator
      containers:
        - name: replicator
          image: quay.io/mittwald/kubernetes-replicator:latest
